version: '3.1'
services:
  mysql:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: auth_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    platform: linux/amd64
    ports:
      - "3306:3306"
  app:
    container_name: app
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass
    ports:
      - "8089:8089"
