
spring:
  application:
    name: Payment Gateway
  datasource:
    username: myuser
    password: mypass
    url: jdbc:mysql://localhost:3306/auth_db
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
app:
  jwt:
    secret: heladslkasdaskdlasdjldasldaslkdasdlaskdalkdjlkasjldkjaslk

#spring.jpa.show-sql: true
debug: true
server:
  port: 8089
